### ISSUE TITLE
Is it a free template to fork?

### ISSUE THREAD

**Issue by Hitaro** [aschepis/aschepis.github.io#1]
:free:  free as freedom, not as a free beer

---

Hey there

Your middleman template is great. Is it available for others too? I couldn't find any license! I also couldn't find a clean fork-able source for this theme in your repos.

Cheers
Hitaro

**Comment by aschepis** [comment]
By all means.. it is free for you to do whatever you like.  I really just hacked it together and so its not very well organized for being reused by others. As long as you don't steal the actual content and pass it off as your own then fork until your heart's content.  if you'd like i can make a branch and delete all the articles.  then you can just download that as a zip

**Comment by onrea** [comment]
> if you'd like i can make a branch and delete all the articles. then you can just download that as a zip

I appreciate it. A new repo will be bettar than a branch. By a new repo others can contribute and you can introduce it in this page: https://directory.middlemanapp.com/#/templates/all with some tags: Community, Presentation, Jquery, Disqus

**Comment by Hitaro** [comment]
> if you'd like i can make a branch and delete all the articles. then you can just download that as a zip

I appreciate it. By a new `repo`/`branch` others can contribute and you can introduce it in this page: https://directory.middlemanapp.com/#/templates/all with some tags: Community, Presentation, Jquery, Disqus

**Comment by onrea** [comment]
It's ideal for a presentation.
